[server]
headless = true
enableCORS = false
port = 10000

[theme]
base="dark"
primaryColor="#1E90FF"
backgroundColor="#000000"
secondaryBackgroundColor="#1A1A1A"
textColor="#FFFFFF"
font="sans serif"
